# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Pull Request Valid

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["master"]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Hugo Check
  Actions-Hugo-Check:
    environment: pre-github-pages
    runs-on: ubuntu-20.04
    env:
      HUGO_VERSION: 0.101.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build with Hugo
        run: |
          hugo \
            --minify \
            --gc \